### ISSUE TITLE
long startup time on ARM system

### ISSUE THREAD

**Issue by neophob** [bojand/mailgun-js#105]
I use request-time to measure how long the deps need to be found with node, because my app needs quite some time to start:

```
# ./node_modules/.bin/require-time
71ms	body-parser
853ms	express
610ms	lodash
4541ms	mailgun-js
72ms	q
332ms	request
```

- Mailgun: v0.7.12
- Platform: armv7l
- Node: v4.4.7
- npm: 3.9.6

any hints how to reduce this long startup time?

**Comment by bojand** [comment]
Hello, the library is actually dynamically constructed at require time. So it reads the API schema and constructs the client. That's why it takes a little bit of time, which might be accentuated on architectures like ARM. I can take a look if there is some way to speed things up, but I doubt there is much room for improvement without significantly changing how the library works.

**Comment by neophob** [comment]
Well the actual painpoint are the needed 141 dependency packages, see http://npm.anvaka.com/#/view/2d/mailgun-js

**Comment by bojand** [comment]
Hmm depending on the features you need, a fair amount could be easily stripped out of the library to make a lighter module:

* If you don't care about promises, `q` and that feature could be removed (by actually removing it from code). 
* Similarly, if you don't care about proxy support `proxy-agent`, and proxy option can be removed.
* If you don't need webhook validation `validateWebhook` and `tsscmp` can be removed.
* If you don't care for `DEBUG` logging, `debug` and all the logging can be removed

All of this would have to be a fork / different module since it changes the library a fair amount and removes features, but it would be pretty easy to do.
